### ISSUE TITLE
Возможности плеера

### ISSUE THREAD

**Issue by x09** [VladimirSaenko/Audio-Player-v1#1]
Добрый день,

Подскажите пожалуйста, вашему плееру можно подать на вход плейлист треков (m3u/xml/json/txt) либо рандомный трек из этого плейлиста.. Лучше если плейлист указывать в виде ссылки, он просто большой чтобы его прямо в код пихать.
 Есть такой функционал?

**Comment by volodymyrsaienko240** [comment]
Добрый день.

Я не совсем понимаю для чего вам это нужно?

**Comment by x09** [comment]
Ну как для чего.. есть NNNN файлов, которые я хотел бы чтобы игрались в рандомном порядке. Значительно проще управлять плейлистом, чем корячить код.

**Comment by volodymyrsaienko240** [comment]
Для проверки такого можете сделать fork этого репозитория и проверить, возможно описанная вами фича может заработать
